### ISSUE TITLE
Test robustness

### ISSUE THREAD

**Issue by cyrilchapon** [mars/heroku-js-runtime-env#10]
Hey :)

Thanks for this great lib. 😀two questions :

1) See [here](https://github.com/mars/heroku-js-runtime-env-buildpack/issues/4)

2) [This test](https://github.com/mars/heroku-js-runtime-env/blob/master/index.js#L23) is problematic. Among "`production` = dynamic runtime config" being too much opiniated, there is also a critical trouble with heroku. Let me explain.

The main purpose of your mecanism is to load a "runTime config" over "compileTime" environment variables. This is necessary, on Heroku, in 2 use cases :
- When "promoting". The promoted slug embed the compileTime environement variables, which are stales, (because it does not re-run `build` scripts which usualy hard-copy env variables to source-code inside frontend builds)
- **But also** when dynamicaly changing environement variable **without rebuilding the app** (through Heroku CLI / user interface inside settings)

This last use case is **only covered in `production` mode** with your mecanism, because of that aforementionned test. I personnaly use `NODE_ENV=staging` on my staging pipeline step, and I'm not willing to change it to `production` for now

I'd change it to
```
if (!runTime.matches(/REACT_APP_VARS_AS_JSON_*/))
```

To have a quick-win. But as suggested [here](https://github.com/mars/heroku-js-runtime-env-buildpack/issues/4), replacing directly to a literal JS object (not a JSON string) would allow us to only go for :

```
// It was already replaced
if (typeof runTime !== 'string')
```

What do you think ?

**Comment by mars** [comment]
Please fork this repo and modify it as you desire. This project is not something I’m investing time into anymore.

**Comment by cyrilchapon** [comment]
Roger that, good point
