### ISSUE TITLE
After an update on env var on Heroku a rebuild is needed to see the new value

### ISSUE THREAD

**Issue by MalenaMoix** [mars/heroku-js-runtime-env#12]
Hello, I have the following situation:

I'm using the heroku-js-runtime-env buildpack to dynamically interpolate the env variables depending on the environment, and that's working properly.
The problem I'm facing is when I change the value of one of those envs.

I have a variable called REACT_APP_LIMIT_NUMBER (just an example of the real name) and it's value is 25. Then on Heroku I go to the "Settings" tab -> "Config vars" section and update that value to 10. The going back to the web app, I continue seeing 25 as the value for that variable. I tried hard refreshing the page and restarting the dynos, but the only thing that worked for me was doing a rebuild.

I was reviewing the code of this library and I could confirm that I have the variable NODE_ENV=production set on Heroku, but it's still not working.

Then going further I inspected on the browser what were the values for runtimeEnv being loaded on line 14 of index.js file of this library (REACT_APP_VARS_AS_JSON):
![runtimeEnv](https://github.com/mars/heroku-js-runtime-env/assets/38184413/c547b0eb-60b4-4a16-850f-48c6197e293a)
And I found out that the value for REACT_APP_LIMIT_NUMBER there continues being 25 (the old value). I don't know if this is related to the issue or if the issue comes from other place.

Also, we have Heroku 20 as our stack if that helps.

Is there something missing?

Thanks in advance!

**Comment by mars** [comment]
I don't know of anything internal to this module that would cause an individual config var not to be picked-up at runtime, while the other vars are updated correctly:

- did you wait for the app's dynos to restart after the config change?
- is the suspect variable set somewhere else in your build or source code?

This module is not maintained or tested anymore, so if this continues to be a problem, I would recommend finding a different solution to runtime config.
