### ISSUE TITLE
slow network connection causes undefined var

### ISSUE THREAD

**Issue by marinav** [mars/heroku-js-runtime-env#8]
Hello,

Thank you for your work !

I noticed that I had a lot of 404 pages like  https://www.mydomain/undefined/blog, in my dynamic links where I use environment variables. Indeed, if I simulate a slow network connection, I first get "undefined" and then the value comes. 

My question is why do not put :

`env = compileTimeEnv` instead of `env = {}`

in loadRuntimeEnv function's catch ? For there to be at least one default value. To overcome my problem I had to add :

`const env = _.isEmpty(runtimeEnv()) ? process.env : runtimeEnv();` 

but it's not very clean.
 
What do you think about this ?

**Comment by mars** [comment]
This module is synchronous, does not use the network, so I am truly baffled about what you’re experiencing.

The runtime variables are intended to be populated (injected into the javascript bundle) when the server starts up, like in create-react-app-buildpack’s [`.profile` script](https://github.com/mars/create-react-app-inner-buildpack/blob/master/.profile.d/inject_react_app_env.sh).

How does your app inject the runtime variables into the bundle?

Are you using my version or a modified `runtimeEnv()` function that makes network requests?

**Comment by marinav** [comment]
Actually I don't understand how this can happen :/

I'm using your runtimeEnv version, and this buildpack : https://github.com/mars/create-react-app-buildpack

**Comment by mars** [comment]
Sounds like asynchronous javascript fun 🎉

What is it that's delayed and then completes? Are you using dynamic `import()`? It seems like there must be something asynchronous that causes your dynamic route value to be undefined?

**Comment by marinav** [comment]
Indeed I use react-loadable it must be the thing that causes this delay. I will look  at this track thank you !
