### ISSUE TITLE
Using Package Locally

### ISSUE THREAD

**Issue by jdmcd** [mars/heroku-js-runtime-env#9]
Hi there,

First off thanks for this great package. It's made my dev-ops process a lot smoother. Quick question - is there any way to use this package locally? Right now I can't do `yarn build && serve build -s` on my computer because I get the following error:

`Runtime env vars cannot be parsed. Content is `{{REACT_APP_VARS_AS_JSON_______…`

I'm assuming that has to do with the fact that the buildpack installs the `profile.d` script which doesn't happen locally. Any ideas?

**Comment by mars** [comment]
I designed this experience to use create-react-app's dev mode when running locally, where the current `process.env` is available & just works. So, there's nothing pre-made to solve this problem. If you want to run production mode locally, then after your build step and before serve/start, you'll need to inject the current env vars into the bundle.

create-react-app-inner-buildpack contains the [production-mode magic](https://github.com/mars/create-react-app-inner-buildpack/blob/master/.profile.d/inject_react_app_env.sh#L25). The [Ruby program](https://github.com/mars/create-react-app-inner-buildpack/blob/master/lib/injectable_env.rb) that performs the bundle injection would need to be extracted to run locally. It uses only the Ruby standard library, so should be pretty simple to run as a standalone Ruby script.

**Comment by jdmcd** [comment]
@mars Awesome, thanks for the prompt reply!
